ShoeShop/Controllers/AdminSiteController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ShoeShop.Models;

namespace ShoeShop.Controllers
{
    public class AdminSiteController : Controller
    {
        private readonly ShoesDbContext db = new ShoesDbContext();

        #region IndexPage

        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        #endregion

        #region ViewAllSize

        /// <summary>
        ///     View lists of size
        /// </summary>
        /// <returns>List Size</returns>
        public ActionResult SizeManage()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            var listSize = db.Sizes.ToList();
            return View(listSize);
        }

        #endregion

        #region DeleteSize

        /// <summary>
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteSize(int id = 0)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            try
            {
                var size = db.Sizes.Find(id);

                if (size == null)
                {
                    return RedirectToAction("Index");
                }

                db.Sizes.Remove(size);
                db.SaveChanges();
                return RedirectToAction("SizeManage");
            }

            catch
            {
                object message = "Không xóa được do ràng buộc csdl ";
                return View("Error", message);
            }
        }

        #endregion

        #region ViewAllCategory

        /// <summary>
        /// </summary>
        /// <returns>List of category item</returns>
        public ActionResult CategoryManage()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            var cat = db.Loais.Where(result => !result.ChungLoaiID.HasValue).ToList();
            return View(cat);
        }

        #endregion

        #region DeleteCat

        /// <summary>
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteCat(int id = 0)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            try
            {
                var cat = db.Loais.Find(id);
                if (cat == null)
                {
                    return RedirectToAction("CategoryManage");
                }
                db.Loais.Remove(cat);
                db.SaveChanges();
                return RedirectToAction("CategoryManage");
            }
            catch (Exception ex)
            {
                object mess = "Không xóa được do " + ex.Message;
                return View("Error", mess);
            }
        }

        #endregion

        #region ViewAllBrand

        /// <summary>
        /// </summary>
        /// <returns></returns>
        public ActionResult BrandManage()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            var cat = db.Loais
                .Select(p => new {p.ID, p.Ten, ChungLoai = p.Loai2.Ten, p.ChungLoaiID, p.BiDanh})
                .Where(result => result.ChungLoaiID.HasValue).ToList();
            return View(cat);
        }

        #endregion

        #region DeleteBrand

        /// <summary>
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteBrand(int id = 0)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            try
            {
                var cat = db.Loais.Find(id);

                if (cat == null)
                {
                    return RedirectToAction("BrandManage");
                }

                db.Loais.Remove(cat);
                db.SaveChanges();
                return RedirectToAction("BrandManage");
            }
            catch (Exception ex)
            {
                object mess = "Không xóa được do " + ex.Message;
                return View("Error", mess);
            }
        }

        #endregion

        #region ViewAllProduct

        /// <summary>
        /// </summary>
        /// <returns></returns>
        public ActionResult ProductManage()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            var product = db.SanPhams.Include(s => s.Loai);
            return View(product);
        }

        #endregion

        #region ProductDetails

        /// <summary>
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ProductDetails(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }

            if (id == null)
            {
                return RedirectToAction("ProductManage");
            }

            var product = db.SanPhams.
                Include("Loai").
                Include("KhuyenMai").
                Include("SanPhamHinhs").
                Include("SanPhamSizes").
                Include("SanPhamSizes.Size").SingleOrDefault(result => result.SanPhamID == id);

            if (product == null)
            {
                return View("404");
            }

            return View(product);
        }

        #endregion

        #region DeleteProduct

        public ActionResult DeleteProduct(int id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }

            try
            {
                var countOrder =
                    db.SanPhamSizes.Count(result => result.SanPhamID == id && result.DonHangChiTiets.Any());

                if (countOrder > 0)
                {
                    throw new Exception("Không hủy được do có đơn đặt hàng");
                }

                var deleteProduct = db.SanPhams
                    .Include(s => s.SanPhamSizes)
                    .Include(i => i.SanPhamHinhs)
                    .SingleOrDefault(result => result.SanPhamID == id);
                db.SanPhamSizes.RemoveRange(deleteProduct.SanPhamSizes);
                db.SanPhamHinhs.RemoveRange(deleteProduct.SanPhamHinhs);

                foreach (var item in deleteProduct.SanPhamHinhs)
                {
                    var fileName = item.TenHinh;
                    var path = Server.MapPath("~/Photos/" + fileName);
                    var file = new FileInfo(path);
                    if (file.Exists)
                    {
                        file.Delete();
                    }
                }

                db.SanPhams.Remove(deleteProduct);
                db.SaveChanges();
                return RedirectToAction("ProductManage");
            }

            catch (Exception ex)
            {
                object mess = "Không xóa được do " + ex.Message;
                return View("Error", mess);
            }
        }

        #endregion

        #region Login - Logout

        /// <summary>
        ///     Login page
        /// </summary>
        /// <returns>get login page</returns>
        public ActionResult Login()
        {
            return View();
        }

        ///// <summary>
        ///// Login page
        ///// </summary>
        ///// <returns>get login page</returns>
        [HttpPost]
        public ActionResult Login(string userName, string passWord)
        {
            var user =
                db.QuanTris.Single(result => result.Username.Equals(userName) && result.Password.Equals(passWord));
            if (user != null)
            {
                Session["user"] = new QuanTri {Username = userName, Level = 1};
                return View("Index", Session["user"]);
            }

            return View();
        }

        /// <summary>
        ///     session destroy
        /// </summary>
        /// <returns>login page</returns>
        public ActionResult LogOff()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }

        #endregion

        #region NewSize

        /// <summary>
        /// </summary>
        /// <returns>Return View for admin</returns>
        public ActionResult NewSize()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }
            return View(new Size());
        }

        /// <summary>
        /// </summary>
        /// <param name="size">Compare size params post back from view the size from source</param>
        /// <returns>New Size</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewSize(Size size)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login");
            }

            var sizeId = db.Sizes.Count(result => result.MaSize.Equals(size.MaSize));
            if (sizeId > 0) ModelState.AddModelError("MaSize", "Mã Size bị trùng");
            var sizeName = db.Sizes.Count(result => result.TenSize.Equals(size.TenSize));
            if (sizeName > 0) ModelState.AddModelError("TenSize", "Tên Size bị trùng");
            if (ModelState.IsValid)
            {
                try
                {
                    db.Sizes.Add(size);
                    db.SaveChanges();

ShoeShop/Views/AdminSite/BrandManage.cshtml
@{
    ViewBag.Title = "BrandManage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    WebGrid grid = new WebGrid(Model,canPage: true, rowsPerPage: 5,ajaxUpdateContainerId:"grid");
    grid.Pager(WebGridPagerModes.All);
}

@Html.ActionLink("Thêm loại mới", "NewBrand", null, new { @class = "btn btn-danger" })
<div class="row well" style="margin:5%">
@grid.GetHtml(tableStyle: "table table-hover ",htmlAttributes: new { id="grid" },
columns: grid.Columns(
        grid.Column("ID", header: "ID"),
        grid.Column("Ten", header: "Tên Loại"),
        grid.Column("ChungLoai", "Chủng Loại"),
        grid.Column("BiDanh", header: "URL"),
        grid.Column(header: "Cập Nhật", format: result => Html.ActionLink("Cập Nhật", "EditBrand", new { id = result.ID }, new { @class = "btn btn-facebook" })),
        grid.Column(header: "Xóa", format: result => Html.ActionLink("Xóa", "DeleteBrand", new { id = result.ID }, htmlAttributes: new { onclick = "return confirm('Bạn có chắc chắn không ?');", @class = "btn btn-danger" }))
)
)
</div>

ShoeShop/Views/AdminSite/CategoryManage.cshtml
@model IEnumerable<ShoeShop.Models.Loai>
@{
    ViewBag.Title = "CategoryManage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@Html.ActionLink("Thêm chủng loại mới", "NewCat", null, new { @class = "btn btn-danger" })
<div class="row well" style="margin:5%">
    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tên Chủng Loại</th>
                    <th>Bí Danh</th>
                    <th>
                        Cập nhật/
                        Xóa
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cat in Model)
                {
                    <tr>
                        <th scope="row">@cat.ID</th>
                        <td>@cat.Ten</td>
                        <td>@cat.BiDanh</td>
                        <td>
                            @Html.ActionLink("Cập nhật", "EditCat", new { id = cat.ID }, new { @class = "btn btn-facebook" })
                            @Html.ActionLink("Xóa", "DeleteCat", new { id = cat.ID }, htmlAttributes: new { onclick = "return confirm('Bạn có chắc chắn không ?');", @class = "btn btn-danger" })
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    </div>
</div>

ShoeShop/Views/AdminSite/EditBrand.cshtml
@model ShoeShop.Models.Loai
@{
    ViewBag.Title = "EditBrand";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@Html.ActionLink("Trở về trang trước", "BrandManage", null, new { @class = "btn btn-primary" })
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal row" style="margin:auto">
        <input type="hidden" value="@Model.ChungLoaiID" name="ChungLoaiID"/>
        <div class="col-md-12 well " style="margin-top:5%">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h3 class="panel-title">Chỉnh sửa chủng loại </h3>
                </div>
                <div class="panel-body">
                    <div class="form-group col-md-6 input-group" style="margin:auto;margin-top:10px">
                        @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "input-group-addon" })
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                    @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger", style = "margin-left:40%" })

                </div>
            </div>
            <button type="submit" class="btn btn-danger btn-block btn-mini" style="margin-top:10px">Thêm</button>

        </div>

    </div>
}


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}
@Html.Raw(TempData["Success_Mess"])
@Html.Raw(TempData["Error_Mess"])

ShoeShop/Views/AdminSite/EditSize.cshtml
@model ShoeShop.Models.Size
@{
    ViewBag.Title = "EditSize";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@Html.ActionLink("Trở về trang trước", "SizeManage", null, new { @class = "btn btn-primary" })
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal row" style="margin:auto">
        <input type="hidden" value="@Model.SizeID" />
        <div class="col-md-12 well " style="margin-top:5%">
            <h3><span class="label label-primary" style="margin-left: 40%;">Thông Tin Size</span></h3>

            <div class="form-group col-md-6 input-group" style="margin:auto;margin-top:10px">

                @Html.LabelFor(model => model.MaSize, htmlAttributes: new { @class = "input-group-addon" })
                @Html.EditorFor(model => model.MaSize, new { htmlAttributes = new { @class = "form-control" } })

            </div>
            @Html.ValidationMessageFor(model => model.MaSize, "", new { @class = "text-danger", style = "margin-left:40%" })
            <div class="form-group col-md-6 input-group" style="margin:auto;margin-top:10px">

                @Html.LabelFor(model => model.TenSize, htmlAttributes: new { @class = "input-group-addon" })
                @Html.EditorFor(model => model.TenSize, new { htmlAttributes = new { @class = "form-control" } })

            </div>
            @Html.ValidationMessageFor(model => model.TenSize, "", new { @class = "text-danger", style = "margin-left:40%" })
            <div class="form-group col-md-6 input-group" style="margin:auto;margin-top:10px;margin-bottom:10px;">

                @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "input-group-addon" })
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })

            </div>
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger", style = "margin-left:40%" })
        </div>
        <button type="submit" class="btn btn-danger btn-block btn-mini" style="margin-top:10px">Thêm</button>
    </div>
}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}
@Html.Raw(TempData["Success_Mess"])

ShoeShop/Views/AdminSite/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Admin Login</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="~/Content/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/admin/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="~/Content/admin/js/jquery.min.js"></script>
    <script src="~/Content/admin/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
    <script src="~/Content/admin/js/bootstrap.min.js" type="text/javascript"></script>

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Login via site</h3>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("Login","AdminSite",FormMethod.Post))
                        {
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="UserName" name="username" type="text">
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="PassWord" name="password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me"> Remember Me
                                    </label>
                                </div>
                                <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
                            </fieldset>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<style>
    .row {
        margin-top:10%;
    }
    .white {
        color: #000;
        background-color: #fff;
    }

    .btn-facebook {
        color: #ffffff;
        -webkit-text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
        text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
        background-color: #2b4b90;
        *background-color: #133783;
        background-image: -moz-linear-gradient(top, #3b5998, #133783);
        background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#3b5998), to(#133783));
        background-image: -webkit-linear-gradient(top, #3b5998, #133783);
        background-image: -o-linear-gradient(top, #3b5998, #133783);
        background-image: linear-gradient(to bottom, #3b5998, #133783);
        background-repeat: repeat-x;
        border-color: #133783 #133783 #091b40;
        border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff3b5998', endColorstr='#ff133783', GradientType=0);
        filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
    }

        .btn-facebook:hover,
        .btn-facebook:focus,
        .btn-facebook:active,
        .btn-facebook.active,
        .btn-facebook.disabled,
        .btn-facebook[disabled] {
            color: #ffffff;
            background-color: #133783 !important;
            *background-color: #102e6d !important;
        }

        .btn-facebook:active,
        .btn-facebook.active {
            background-color: #0d2456 \9 !important;
        }
</style>

ShoeShop/Views/AdminSite/NewBrand.cshtml
@model ShoeShop.Models.Loai
@{
    ViewBag.Title = "NewCat";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@Html.ActionLink("Trở về trang trước", "BrandManage", null, new { @class = "btn btn-primary" })
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal row" style="margin:auto">

        <div class="col-md-12 well " style="margin-top:5%">
            <div class="panel panel-primary ">
                <div class="panel-heading">
                    <h3 class="panel-title">Thêm loại </h3>
                </div>
                <div class="panel-body">
                    <div class="form-group col-md-6 input-group" style="margin:auto;margin-top:10px">
                        @Html.LabelFor(model => model.Ten,"Tên Loại", htmlAttributes: new { @class = "input-group-addon" })
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                    @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger", style = "margin-left:40%" })

                    <div class="form-group col-md-6 input-group" style="margin:auto;margin-top:10px">
                        @Html.LabelFor(model => model.Ten, "Chủng Loại", htmlAttributes: new { @class = "input-group-addon" })
                        @Html.DropDownList("ChungLoaiID", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
           
                    
                    

    
            </div>
            <button type="submit" class="btn btn-danger btn-block btn-mini" style="margin-top:10px">Thêm</button>

        </div>

    </div>
}


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}
@Html.Raw(TempData["Success_Mess"])

ShoeShop/Views/AdminSite/UploadImg.cshtml
@model ShoeShop.Models.SanPham
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    WebGrid grid = new WebGrid(@Model.SanPhamHinhs);
    string path = Url.Content("~/Photos/");
}


@using (Html.BeginForm("UploadImg", "AdminSite", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <article class="panel panel-info">
        @Html.HiddenFor(model => model.SanPhamID)
        <div class="panel-heading icon">
            <i class="glyphicon glyphicon-picture"></i>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên hình</th>
                        <th>Thứ tự hiển thị</th>
                        <th>Ảnh</th>
                        <th>Xóa</th>
                    </tr>
                </thead>
                @foreach (var item in @Model.SanPhamHinhs)
                {

                    <tbody>
                        <tr>
                            <th>@item.SanPhamHinhID</th>
                            <th>@item.TenHinh</th>
                            <th>@item.ThuTuHienThi</th>
                            <th><img src="~/Photos/@item.TenHinh" width="150" height="150" /></th>
                            <th>@Html.ActionLink("X", "DeleteImg", new { id = item.SanPhamHinhID,SanPhamID=item.SanPhamID }, htmlAttributes: new { onclick = "return confirm('Bạn có chắc chắn không ?');", @class = "btn btn-circle brn-danger" })</th>
                        </tr>
                    </tbody>

                }
            </table>

        </div>
        <div class="panel-heading">
            <h2 class="panel-title">Upload Hình</h2>
        </div>
        <div class="panel-body">

            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">File 1:</label>
                    <div class="col-md-10">
                        <input type="file" name="files" id="file1" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">File 2:</label>
                    <div class="col-md-10">
                        <input type="file" name="files" id="file2" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">File 3:</label>
                    <div class="col-md-10">
                        <input type="file" name="files" id="file3" class="form-control" />
                    </div>
                </div>

            </div>
            <input type="hidden" name="id" value="@Model.SanPhamID" id="spID" />
            <input type="submit" value="Upload" class="btn btn-primary btn-block" />
        </div>

    </article>

 
}
<style type="text/css">
    .timeline {
        position: relative;
        padding: 21px 0px 10px;
        margin-top: 4px;
        margin-bottom: 30px;
    }

        .timeline .line {
            position: absolute;
            width: 4px;
            display: block;
            background: currentColor;
            top: 0px;
            bottom: 0px;
            margin-left: 30px;
        }

        .timeline .separator {
            border-top: 1px solid currentColor;
            padding: 5px;
            padding-left: 40px;
            font-style: italic;
            font-size: .9em;
            margin-left: 30px;
        }

        .timeline .line::before {
            top: -4px;
        }

        .timeline .line::after {
            bottom: -4px;
        }

        .timeline .line::before,
        .timeline .line::after {
            content: '';
            position: absolute;
            left: -4px;
            width: 12px;
            height: 12px;
            display: block;
            border-radius: 50%;
            background: currentColor;
        }

        .timeline .panel {
            position: relative;
            margin: 10px 0px 21px 70px;
            clear: both;
        }

            .timeline .panel::before {
                position: absolute;
                display: block;
                top: 8px;
                left: -24px;
                content: '';
                width: 0px;
                height: 0px;
                border: inherit;
                border-width: 12px;
                border-top-color: transparent;
                border-bottom-color: transparent;
                border-left-color: transparent;
            }

            .timeline .panel .panel-heading.icon * {
                font-size: 20px;
                vertical-align: middle;
                line-height: 40px;
            }

            .timeline .panel .panel-heading.icon {
                position: absolute;
                left: -59px;
                display: block;
                width: 40px;
                height: 40px;
                padding: 0px;
                border-radius: 50%;
                text-align: center;
                float: left;
            }

        .timeline .panel-outline {
            border-color: transparent;
            background: transparent;
            box-shadow: none;
        }

            .timeline .panel-outline .panel-body {
                padding: 10px 0px;
            }

            .timeline .panel-outline .panel-heading:not(.icon),
            .timeline .panel-outline .panel-footer {
                display: none;
            }

    .img-rounded {
        float: left;
    }

        .img-rounded img {
            width: 150px;
            height: 200px;
        }

    .material-switch > input[type="radio"] {
        display: none;
    }

    .material-switch > label {
        cursor: pointer;
        height: 0px;
        position: relative;
        width: 40px;
    }

        .material-switch > label::before {
            background: rgb(0, 0, 0);
            box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.5);
            border-radius: 8px;
            content: '';
            height: 16px;
            margin-top: -8px;
            position: absolute;
            opacity: 0.3;
            transition: all 0.4s ease-in-out;
            width: 40px;
        }

        .material-switch > label::after {
            background: rgb(255, 255, 255);
            border-radius: 16px;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
            content: '';
            height: 24px;
            left: -4px;
            margin-top: -8px;
            position: absolute;
            top: -4px;
            transition: all 0.3s ease-in-out;
            width: 24px;
        }

    .material-switch > input[type="radio"]:checked + label::before {
        background: inherit;
        opacity: 0.5;
    }

    .material-switch > input[type="radio"]:checked + label::after {
        background: inherit;
        left: 20px;
    }

    .checkbox label:after,
    .radio label:after {
        content: '';
        display: table;
        clear: both;
    }

    .checkbox .cr,
    .radio .cr {
        position: relative;
        display: inline-block;
        border: 1px solid #a9a9a9;
        border-radius: .25em;
        width: 1.3em;
        height: 1.3em;
        float: left;
        margin-right: .5em;
    }

    .radio .cr {
        border-radius: 50%;
    }

        .checkbox .cr .cr-icon,
        .radio .cr .cr-icon {
            position: absolute;
            font-size: .8em;
            line-height: 0;
            top: 50%;
            left: 20%;
        }

        .radio .cr .cr-icon {
            margin-left: 0.04em;
        }

    .checkbox label input[type="checkbox"],
    .radio label input[type="radio"] {
        display: none;
    }

        .checkbox label input[type="checkbox"] + .cr > .cr-icon,
        .radio label input[type="radio"] + .cr > .cr-icon {
            transform: scale(3) rotateZ(-20deg);
            opacity: 0;
            transition: all .3s ease-in;
        }

        .checkbox label input[type="checkbox"]:checked + .cr > .cr-icon,
        .radio label input[type="radio"]:checked + .cr > .cr-icon {
            transform: scale(1) rotateZ(0deg);
            opacity: 1;
        }

        .checkbox label input[type="checkbox"]:disabled + .cr,
        .radio label input[type="radio"]:disabled + .cr {
            opacity: .5;
        }
</style>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}@Html.Raw(TempData["Success_Mess"])